"""A100/SM80 specific GRU kernel prototypes."""

from .gru_forward import (
    a100_gru_forward_from_gates,
    a100_gru_forward_from_gates_cooperative,
    a100_gru_forward_from_gates_cooperative_h256,
    a100_gru_forward_from_gates_cooperative_h256_cached_shmem,
    a100_gru_forward_from_gates_cooperative_h256_parallel_update,
    a100_gru_forward_from_gates_cooperative_h256_qwarp_shmem,
    a100_gru_forward_from_gates_cooperative_h256_shmem,
    a100_gru_forward_from_gates_fused,
    a100_gru_forward_from_gates_fused_pingpong,
    a100_gru_forward_from_gates_fused_specialized,
    a100_gru_forward_from_gates_subwarp,
    a100_gru_forward_layer,
    a100_gru_forward_layer_precompute_input_cooperative,
    a100_gru_forward_layer_precompute_input_cooperative_h256,
    a100_gru_forward_layer_precompute_input_cooperative_h256_cached_shmem,
    a100_gru_forward_layer_precompute_input_cooperative_h256_parallel_update,
    a100_gru_forward_layer_precompute_input_cooperative_h256_qwarp_shmem,
    a100_gru_forward_layer_precompute_input_cooperative_h256_shmem,
    a100_gru_forward_layer_precompute_input_fused,
    a100_gru_forward_layer_precompute_input_fused_pingpong,
    a100_gru_forward_layer_precompute_input_fused_specialized,
    a100_gru_forward_layer_precompute_input,
    a100_gru_forward_layer_precompute_input_subwarp,
)

__all__ = [
    "a100_gru_forward_from_gates",
    "a100_gru_forward_from_gates_cooperative",
    "a100_gru_forward_from_gates_cooperative_h256",
    "a100_gru_forward_from_gates_cooperative_h256_cached_shmem",
    "a100_gru_forward_from_gates_cooperative_h256_parallel_update",
    "a100_gru_forward_from_gates_cooperative_h256_qwarp_shmem",
    "a100_gru_forward_from_gates_cooperative_h256_shmem",
    "a100_gru_forward_from_gates_fused",
    "a100_gru_forward_from_gates_fused_pingpong",
    "a100_gru_forward_from_gates_fused_specialized",
    "a100_gru_forward_from_gates_subwarp",
    "a100_gru_forward_layer",
    "a100_gru_forward_layer_precompute_input_cooperative",
    "a100_gru_forward_layer_precompute_input_cooperative_h256",
    "a100_gru_forward_layer_precompute_input_cooperative_h256_cached_shmem",
    "a100_gru_forward_layer_precompute_input_cooperative_h256_parallel_update",
    "a100_gru_forward_layer_precompute_input_cooperative_h256_qwarp_shmem",
    "a100_gru_forward_layer_precompute_input_cooperative_h256_shmem",
    "a100_gru_forward_layer_precompute_input_fused",
    "a100_gru_forward_layer_precompute_input_fused_pingpong",
    "a100_gru_forward_layer_precompute_input_fused_specialized",
    "a100_gru_forward_layer_precompute_input",
    "a100_gru_forward_layer_precompute_input_subwarp",
]
